# build container with Dockerfile from github
# https://github.com/heinz-otto/fhem-docker
services:
  fhem:
    build:
      context: https://raw.githubusercontent.com/heinz-otto/fhem-docker/main/DockerfileDeb
      args: 
        - PACKAGE_SIZE=full
    
    container_name: fhem
    hostname: fhem
    restart: always
    ports:
      - "8083:8083"
    environment:
      - TZ=Europe/Berlin
      - LC_ALL
      - LANG
    volumes:
      - "./fhem/:/opt/fhem/"
